const profiles = [
  {
    name: "Ankita Malik",
    role: "Student",
    bio: "Aspiring Full Stack Web Developer",
    skills: ["react", "html", "css", "javascript"],
    github: "AnkitaMalik22",
    twitter: "ankiitamalik",
    instagram: "ankiitamalik",
  },
  {
    name: "Sahil Rohera",
    role: "Student",
    bio: "Full Stack Web Developer",
    skills: [
      "react.js",
      "html",
      "css",
      "javascript",
      "node.js",
      "express.js",
      "mongodb",
    ],
    github: "sahilrohera10",
    twitter: "SahilRohera10",
    instagram: "sahilrohera10",
  },
  {
    name: "William Monroy",
    role: "Student & Software Engineer",
    bio: "Full Stack Developer",
    skills: [
      "git",
      "NextJs",
      "ReactJs",
      "React Native",
      "HTML",
      "CSS",
      "JavaScript",
      "NodeJs",
      "Express",
      "MongoDB",
      "Firebase",
      "SQL",
      "Jest",
      "C++",
      "Python",
      "Java",
      "Figma",
      "Adobe XD",
    ],
    github: "william-monroy",
    twitter: "WmmDev",
    instagram: "william.monroy.m",
  },
  {
    name: "Thomas Qvidahl",
    role: "Software Engineer",
    bio: "Full Stack Developer",
    skills: ["react", "html", "css", "kotlin"],
    github: "tplive",
    twitter: "qvidahl",
    instagram: "tplive",
  },

  {
    name: "Anisha Nayaju",
    role: "student",
    bio: "Backend Development",
    skills: ["html", "CSS", "Javascript", "Python", "C", "c++"],
    github: "anishaxtha",
    twitter: "anishanayaju_26",
    instagram: "anishaxtha08",
  },

  {
    name: "Sarthak Rajput",
    role: "Student",
    bio: "Aspiring Full Stack Developer",
    skills: ["react", "html", "css", "Javascript"],
    github: "rsarthak",
    instagram: "sarthak_raj_put",
  },

  {
    name: "Andrew McDonald",
    role: "Educational Consultant",
    bio: "Educational Concultant",
    skills: ["Scratch", "html", "python"],
    github: "afmcdnL",
    twitter: "afmcdnL",
    instagram: "afmcdnL",
  },

  {
    name: "Roshan Kc",
    role: "Student",
    bio: "Full Stack Developer",
    skills: [
      "Python",
      "Django",
      "React",
      "NextJs",
      "AWS",
      "Security Researcher",
    ],
    github: "Roshankc682",
    twitter: "roshan_kc682",
    instagram: "N/A",
  },
  {
    name: "Sahil Arora",
    role: "Student",
    bio: "Full Stack Developer",
    skills: [
      "ReactJs",
      "Html",
      "css",
      "Javascript",
      "NodeJs",
      "Express",
      "Mongodb",
      "Sql",
      "C++",
      "git",
    ],
    github: "sahilarora02",
    twitter: "arorasahil002",
    instagram: "im_sahil_002",
  },
  {
    name: "Arun Jangra",
    role: "Student",
    bio: "Full Stack Web3 Developer",
    skills: ["react", "nodejs", "express", "typescript", "solidity", "web3.js"],
    github: "Arun89-crypto",
    twitter: "w3Ts0ck3T",
    instagram: "yopiter._.kick",
  },

  {
    name: "Tirth Patel",
    role: "Student",
    bio: "Flutter Developer",
    skills: ["Flutter", "Dart"],
    github: "tirthkp",
    twitter: "tirthkp",
    instagram: "tirthkp",
  },

  {
    name: "Aditi Chauhan",
    role: "Student",
    bio: "Aspiring Full Stack Developer",
    skills: ["react", "html", "css", "javascript", "python"],
    github: "Aditi-1709",
    twitter: "don't have",
    instagram: "don't have ",
  },

  {
    name: "Tirth Patel",
    role: "Student",
    bio: "Flutter Developer",
    skills: ["Flutter", "Dart"],
    github: "tirthkp",
    twitter: "tirthkp",
    instagram: "tirthkp",
  },

  {
    name: "Aditi Chauhan",
    role: "Student",
    bio: "Aspiring Full Stack Developer",
    skills: ["react", "html", "css", "javascript", "python"],
    github: "Aditi-1709",
    twitter: "don't have",
    instagram: "don't have ",
  },
  {
    name: "Sai Karthik",
    role: "Software Engineer",
    bio: "Frontend Developer",
    skills: ["ReactJs", "Html", "css", "Javascript"],
    github: "sai-karthik-p",
    twitter: "SaikarthikP",
    instagram: "_.sai_karthik._",
  },

  {
    name: "Souvik Das",
    role: "Student",
    bio: "Aspiring Developer - App and Web",
    skills: ["react", "html", "css", "javascript", "python", "Swift"],
  },
  {
    name: "Hijikesh Hijal",
    role: "Software Engineer",
    bio: "Full Stack Developer",
    skills: [
      "JavaScript",
      "Node",
      "React",
      "VueJs",
      "Express",
      "Restify",
      "MySQL",
      "PostgreSQL",
      "MongoDB",
    ],
    github: "hijal",
    twitter: "hiijal",
    instagram: "",
  },
  {
    name: "Stuti Kumari",
    role: "Software Engineer",
    bio: "Front-End Developer",

    skills: ["Html", "Css", "JavaScript", "React", "Tailwind", "MaterialUi"],
  },
  {
    name: "Shaurya Sk",
    role: "FrontEnd developer",
    bio: "Front-End Developer",
    skills: ["Html", "Css", "JavaScript", "React", "Tailwind", "MaterialUi"],
    github: "Shaurya",
    twitter: "ShauryaKumar",
    instagram: "SShaurya",
  },
  {
    name: "Dhruvil Lakhtaria",
    role: "Student",
    bio: "Aspiring Software Engineer",
    skills: ["JavaScript", "Node", "React", "Express", "MySQL", "MongoDB"],
    github: "Dhruvil-Lakhtaria",
    twitter: "",
    instagram: "dhruvil.lakhtaria",
  },
  {
    name: "Indudini Thennakoon",
    role: "Student at SLIIT",
    bio: "Web Developer and Content Writer",
    skills: ["html", "css", "c", "c++", "php", "MySQL", "JavaScript", "git"],
    github: "IndudiniThennakoon",
    twitter: "indudini thennakoon",
    instagram: "Indudini Thennakoon",
  },
  {
    name: "Vedang Mule",
    role: "Student at VIT Mumbai",
    bio: "Web Developer and Competitive programmer",
    skills: [
      "html",
      "css",
      "javascript",
      "c++",
      "React",
      "Express",
      "Java",
      "git",
    ],
    github: "developer208",
    twitter: "Vedang208",
    instagram: "lazy_coder208",
  },

  {
    name: "Ayush kumar",
    role: "Student",
    bio: "student at NITK",
    skills: ["JavaScript", "React", "MySQL", "PostgreSQL", "python"],
    github: "ayush4345",
    twitter: "ayushk_43",
  },

  {
    name: "Mohamed Khaled Yousef",
    role: "Frontend Developer",
    bio: "Frontend Developer",
    skills: ["Html", "Css", "JavaScript", "React", "Tailwind", "MaterialUi", "Nextjs", "Typescript"],
    github: "this-mkhy",
    twitter: "this_mkhy",
    instagram: "this_mkhy",
  },

  {
    name: "Vedang Mule",
    role: "Student at VIT Mumbai",
    bio: "Web Developer and Competitive programmer",
    skills: [
      "html",
      "css",
      "javascript",
      "c++",
      "React",
      "Express",
      "Java",
      "git",
    ],
    github: "developer208",
    twitter: "Vedang208",
    instagram: "lazy_coder208",
  },

  {
    name: "Vedang Mule",
    role: "Student at VIT Mumbai",
    bio: "Web Developer and Competitive programmer",
    skills: [
      "html",
      "css",
      "javascript",
      "c++",
      "React",
      "Express",
      "Java",
      "git",
    ],
    github: "developer208",
    twitter: "Vedang208",
    instagram: "lazy_coder208",
  },

  {
    name: "Logadheep",
    role: "Student",
    bio: "Python Enthusiast and Competitive Programmer",
    skills: ["html", "css", "javascript", "c++", "python", "java"],
    github: "Logadheep",
    twitter: "LogadheepN",
    instagram: "__loga45__",
  },
  {
    name: "Indudini Thennakoon",
    role: "Student at SLIIT",
    bio: "Web Developer and Content Writer",
    skills: ["html", "css", "c", "c++", "php", "MySQL", "JavaScript", "git"],
    github: "IndudiniThennakoon",
    twitter: "indudini thennakoon",
    instagram: "Indudini Thennakoon",
  },
  {
    name: "Madhusha Prasad",
    role: "Student at SLIIT",
    bio: "UI/UX,Full Stack Web and Mobile App Developer",
    skills: [
      "html",
      "css",
      "Bootstrap",
      "Tailwind",
      "Java",
      "c",
      "c++",
      "php",
      "Dart",
      "JavaScript",
      "TypeScript",
      "ReactJs",
      "NextJS",
      "VueJs",
      "Angular",
      "Node",
      "Express",
      "MySQL",
      "MongoDB",
      "git",
    ],
    github: "MadhushaPrasad",
    twitter: "MadhushaPrasad",
    instagram: "iam_mprasad",
  },
  {
    name: "Vedang Mule",
    role: "Student at VIT Mumbai",
    bio: "Web Developer and Competitive programmer",
    skills: [
      "html",
      "css",
      "javascript",
      "c++",
      "React",
      "Express",
      "Java",
      "git",
    ],
    github: "developer208",
    twitter: "Vedang208",
    instagram: "lazy_coder208",
  },
  {
    name: "Logadheep",
    role: "Student",
    bio: "Python Enthusiast and Competitive Programmer",
    skills: ["html", "css", "javascript", "c++", "python", "java"],
    github: "Logadheep",
    twitter: "LogadheepN",
    instagram: "__loga45__",
  },

  {
    name: "Yashneet Kalra",
    role: "Student",
    bio: "Aspiring software engineer who loves to explore new technologies",
    skills: [
      "Python",
      "Flask",
      "Django",
      "C/C++",
      "Postman",
      "Html",
      "CSS",
      "Javascript",
    ],
    github: "https://github.com/yashneet-kalra",
    twitter: "",
    instagram: "",
  },
  {
    name: "Yagnesh Patel",
    role: "Student",
    bio: "Java Developer",
    skills: ["Java", "C", "html", "css", "javascript"],
    github: "yaggit",
  },
  {
    name: "Rohit Roy",
    role: "Full Stack Developer, Student CSE' 24",
    bio: "I'm an CS engineer and a aspiring Full Stack Developer in making. I love coding, development and currently I'm also focusing into learning Blockchain currently.",
    skills: [
      "HTML",
      "CSS",
      "Javascript",
      "React",
      "Node JS",
      "C++",
      "Java",
      "Python",
      "Solidity",
      "SQL",
    ],
    github: "rohitroy-github",
    twitter: "rohitroy_R",
    instagram: "rohit_roy_x",

  },



  {
    name: "Siddhi Agarkar",
    role: "Sophomore at NIT DGP",
    bio: "Full Stack Web-developer and enthusiastic learner. ",
    skills: [
      "Python",
      "Django",
      "C++",
      "Postman",
      "Html",
      "CSS",
      "Javascript",
    ],
    github: "https://github.com/siddhiagarkar",
    twitter: "",
    instagram: "seedhee1203",
    },
    {
    name: "Kashika Malik",
    role: "Student",
    bio: "Aspiring Programmer",
    skills: ["python", "javascript"],
    github: "s-malikk",
  },

  {
    name: "Richa Roy",
    role: "Student",
    bio: "Aspiring full stack developer and Competitive coding enthusiast",
    skills: ["html", "css", "javascript","c++"],
    github: "richaroy7",
    twitter: "Richaaaaa77",
    instagram: "richaroy_07",
  },

  {
    name: "Dipanjana Dasgupta",
    role: "Student",
    bio: "Aspiring full stack developer and Competitive coding enthusiast",
    skills: ["html", "css", "javascript","c++","python","java"],
    github: "Dipanjana25",
    twitter: "dipanjana12345",
    instagram: "dipanjanadasgupta",
  }


];

export default profiles;
