const profiles = [
  {
    name: "Ankita Malik",
    role: "Student",
    bio: "Aspiring Full Stack Web Developer",
    skills: ["react", "html", "css", "javascript"],
    github: "AnkitaMalik22",
    twitter: "ankiitamalik",
    instagram: "ankiitamalik",
  },
  {
    name: "Thomas Qvidahl",
    role: "Software Engineer",
    bio: "Full Stack Developer",
    skills: ["react", "html", "css", "kotlin"],
    github: "tplive",
    twitter: "qvidahl",
    instagram: "tplive",
  },

  {
    name: "Sarthak Rajput",
    role: "Student",
    bio: "Aspiring Full Stack Developer",
    skills: ["react", "html", "css", "Javascript"],
    github: "rsarthak",
    instagram: "sarthak_raj_put",
  },

  {
    name: "Andrew McDonald",
    role: "Educational Consultant",
    bio: "Educational Concultant",
    skills: ["Scratch", "html", "python"],
    github: "afmcdnL",
    twitter: "afmcdnL",
    instagram: "afmcdnL",
  },

  {
    name: "Roshan Kc",
    role: "Student",
    bio: "Full Stack Developer",
    skills: [
      "Python",
      "Django",
      "React",
      "NextJs",
      "AWS",
      "Security Researcher",
    ],
    github: "Roshankc682",
    twitter: "roshan_kc682",
    instagram: "N/A",
  },

  {
    name: "Arun Jangra",
    role: "Student",
    bio: "Full Stack Web3 Developer",
    skills: ["react", "nodejs", "express", "typescript", "solidity", "web3.js"],
    github: "Arun89-crypto",
    twitter: "w3Ts0ck3T",
    instagram: "yopiter._.kick",
  },

  {
    name: "Tirth Patel",
    role: "Student",
    bio: "Flutter Developer",
    skills: ["Flutter", "Dart"],
    github: "tirthkp",
    twitter: "tirthkp",
    instagram: "tirthkp",
  },

  {
    name: "Aditi Chauhan",
    role: "Student",
    bio: "Aspiring Full Stack Developer",
    skills: ["react", "html", "css", "javascript", "python"],
    github: "Aditi-1709",
    twitter: "don't have",
    instagram: "don't have ",
  },

  {
    name: "Tirth Patel",
    role: "Student",
    bio: "Flutter Developer",
    skills: ["Flutter", "Dart"],
    github: "tirthkp",
    twitter: "tirthkp",
    instagram: "tirthkp",
  },

  {
    name: "Aditi Chauhan",
    role: "Student",
    bio: "Aspiring Full Stack Developer",
    skills: ["react", "html", "css", "javascript", "python"],
    github: "Aditi-1709",
    twitter: "don't have",
    instagram: "don't have ",
  },
  {
    name: "Sai Karthik",
    role: "Software Engineer",
    bio: "Frontend Developer",
    skills: ["ReactJs", "Html", "css", "Javascript"],
    github: "sai-karthik-p",
    twitter: "SaikarthikP",
    instagram: "_.sai_karthik._",
  },

  {
    name: "Souvik Das",
    role: "Student",
    bio: "Aspiring Developer - App and Web",
    skills: ["react", "html", "css", "javascript", "python", "Swift"],
  },
  {
    name: "Hijikesh Hijal",
    role: "Software Engineer",
    bio: "Full Stack Developer",
    skills: [
      "JavaScript",
      "Node",
      "React",
      "VueJs",
      "Express",
      "Restify",
      "MySQL",
      "PostgreSQL",
      "MongoDB",
    ],
    github: "hijal",
    twitter: "hiijal",
    instagram: "",
  },
  {
    name: "Stuti Kumari",
    role: "Software Engineer",
    bio: "Front-End Developer",
    skills: [
      "Html",
      "Css",
      "JavaScript",
      "React",
      "Tailwind",
      "MaterialUi",
    ],
   
  },
  {
    name: "Shaurya Sk",
    role: "FrontEnd developer",
    bio: "Front-End Developer",
    skills: [
      "Html",
      "Css",
      "JavaScript",
      "React",
      "Tailwind",
      "MaterialUi",
    ],
    github: "Shaurya",
    twitter: "ShauryaKumar",
    instagram: "SShaurya",
    },
  {
    name: "Dhruvil Lakhtaria",
    role: "Student",
    bio: "Aspiring Software Engineer",
    skills: ["JavaScript", "Node", "React", "Express", "MySQL", "MongoDB"],
    github: "Dhruvil-Lakhtaria",
    twitter: "",
    instagram: "dhruvil.lakhtaria",

  },
  {
    name: "Indudini Thennakoon",
    role: "Student at SLIIT",
    bio: "Web Developer and Content Writer",
    skills: [ "html", "css", "c", "c++", "php", "MySQL","JavaScript","git"],
    github: "IndudiniThennakoon",
    twitter: "indudini thennakoon",
    instagram: "Indudini Thennakoon",
    },

];

export default profiles;
