const SKILLS = [
  { name: "HTML" },
  { name: "CSS" },
  { name: "JavaScript" },
  { name: "ReactJs" },
  { name: "NodeJs" },
  { name: "SQL" },
  { name: "NextJs" },
  { name: "Java" },
  { name: "Flutter" },
  { name: "Dart" },
  { name: "Solidity" },
  { name: "Express" },
  { name: "MongoDB" },
  { name: "Web3.js" },
  { name: "Swift" },
  { name: "VueJs" },
  { name: "Restify" },
  { name: "PostgreSQL" },
  { name: "css" },
  { name: "Bootstrap" },
  { name: "Tailwind" },
  { name: "php" },
  { name: "C" },
  { name: "C++" },
  { name: "git" },
  { name: "Machine Learning" },
  { name: "Deep Learning" },
  { name: "Python" },
  { name: ".Net" },
  { name: "AngularJS"},
  { name: "Material UI" },
  { name: "WordPress" },
  { name: "React Native" },
  { name: "Firebase" },
  { name: "Jest" },
  { name: "Figma" },
  { name: "AdobeXD" },




];

export default SKILLS;
